version: "3.9"
services:
  spacebarchat:
    build:
      context: .
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - spacebarchat-storage:/exec/persistent/storage
    environment:
      DATABASE: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
      STORAGE_PROVIDER: "file"
      STORAGE_LOCATION: "/exec/persistent/storage/"
      PORT: "3001"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DATABASE:?err}
    ports:
      - '127.0.0.1:5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=${NGINX_HOST:?err}
      - MAIL_CERTBOT=${MAIL_CERTBOT:?err}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-site:/etc/nginx/sites-enabled/
      - letsencrypt-folder:/etc/letsencrypt
    depends_on: 
      - spacebarchat
volumes:
  spacebarchat-storage:
  db:
  nginx-site:
  letsencrypt-folder: