# syntax=docker/dockerfile:1
From node:16-bullseye as builder

WORKDIR devel/
RUN apt-get update ; apt-get upgrade -y ; apt-get install -y python-is-python3 build-essential git
RUN git clone https://github.com/spacebarchat/spacebarchat-server.git
RUN cd spacebarchat-server ; npm i ; npm run setup

From node:16-alpine

EXPOSE 3001
WORKDIR exec
RUN mkdir -p persistent/database ; mkdir -p persistent/storage
RUN apk add --update git ; npm install pg --save
COPY --from=builder /devel/spacebarchat-server/ . 
RUN adduser -D spacebarchat ; chown spacebarchat:spacebarchat -R .

USER spacebarchat

CMD ["npm", "run", "start"]
